# coding: utf-8

"""
    声纹云api

    api document  # noqa: E501

    OpenAPI spec version: /cloudapi/v1beta
    Contact: xiachengjia@speakin.mobi
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.voiceprinttopn_verify_response import VoiceprinttopnVerifyResponse  # noqa: E501
from openapi_client.rest import ApiException


class TestVoiceprinttopnVerifyResponse(unittest.TestCase):
    """VoiceprinttopnVerifyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVoiceprinttopnVerifyResponse(self):
        """Test VoiceprinttopnVerifyResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.voiceprinttopn_verify_response.VoiceprinttopnVerifyResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
