# coding: utf-8

"""
    声纹云api

    api document  # noqa: E501

    OpenAPI spec version: /cloudapi/v1beta
    Contact: xiachengjia@speakin.mobi
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.voiceprint_api import VoiceprintApi  # noqa: E501
from openapi_client.rest import ApiException


class TestVoiceprintApi(unittest.TestCase):
    """VoiceprintApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.voiceprint_api.VoiceprintApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete(self):
        """Test case for delete

        """
        pass

    def test_query(self):
        """Test case for query

        """
        pass

    def test_register(self):
        """Test case for register

        """
        pass

    def test_threshold(self):
        """Test case for threshold

        """
        pass

    def test_verify(self):
        """Test case for verify

        """
        pass

    def test_verify1ton(self):
        """Test case for verify1ton

        """
        pass

    def test_verifytopn(self):
        """Test case for verifytopn

        """
        pass


if __name__ == '__main__':
    unittest.main()
