# coding: utf-8

"""
    声纹云api

    api document  # noqa: E501

    OpenAPI spec version: /cloudapi/v1beta
    Contact: xiachengjia@speakin.mobi
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.voiceprint_threshold_request import VoiceprintThresholdRequest  # noqa: E501
from openapi_client.rest import ApiException


class TestVoiceprintThresholdRequest(unittest.TestCase):
    """VoiceprintThresholdRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVoiceprintThresholdRequest(self):
        """Test VoiceprintThresholdRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.voiceprint_threshold_request.VoiceprintThresholdRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
