# coding: utf-8

"""
    声纹云api

    api document  # noqa: E501

    OpenAPI spec version: /cloudapi/v1beta
    Contact: xiachengjia@speakin.mobi
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.storage_api import StorageApi  # noqa: E501
from openapi_client.rest import ApiException


class TestStorageApi(unittest.TestCase):
    """StorageApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.storage_api.StorageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_download(self):
        """Test case for download

        """
        pass

    def test_upload(self):
        """Test case for upload

        """
        pass


if __name__ == '__main__':
    unittest.main()
