# coding: utf-8

"""
    声纹云api

    api document  # noqa: E501

    OpenAPI spec version: /cloudapi/v1beta
    Contact: xiachengjia@speakin.mobi
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class RespVoiceprintVerifyMultiResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'has_error': 'bool',
        'error_id': 'str',
        'error_desc': 'str',
        'data': 'VoiceprintVerifyMultiResponse'
    }

    attribute_map = {
        'has_error': 'hasError',
        'error_id': 'errorId',
        'error_desc': 'errorDesc',
        'data': 'data'
    }

    def __init__(self, has_error=None, error_id=None, error_desc=None, data=None):  # noqa: E501
        """RespVoiceprintVerifyMultiResponse - a model defined in OpenAPI"""  # noqa: E501

        self._has_error = None
        self._error_id = None
        self._error_desc = None
        self._data = None
        self.discriminator = None

        if has_error is not None:
            self.has_error = has_error
        if error_id is not None:
            self.error_id = error_id
        if error_desc is not None:
            self.error_desc = error_desc
        if data is not None:
            self.data = data

    @property
    def has_error(self):
        """Gets the has_error of this RespVoiceprintVerifyMultiResponse.  # noqa: E501


        :return: The has_error of this RespVoiceprintVerifyMultiResponse.  # noqa: E501
        :rtype: bool
        """
        return self._has_error

    @has_error.setter
    def has_error(self, has_error):
        """Sets the has_error of this RespVoiceprintVerifyMultiResponse.


        :param has_error: The has_error of this RespVoiceprintVerifyMultiResponse.  # noqa: E501
        :type: bool
        """

        self._has_error = has_error

    @property
    def error_id(self):
        """Gets the error_id of this RespVoiceprintVerifyMultiResponse.  # noqa: E501


        :return: The error_id of this RespVoiceprintVerifyMultiResponse.  # noqa: E501
        :rtype: str
        """
        return self._error_id

    @error_id.setter
    def error_id(self, error_id):
        """Sets the error_id of this RespVoiceprintVerifyMultiResponse.


        :param error_id: The error_id of this RespVoiceprintVerifyMultiResponse.  # noqa: E501
        :type: str
        """

        self._error_id = error_id

    @property
    def error_desc(self):
        """Gets the error_desc of this RespVoiceprintVerifyMultiResponse.  # noqa: E501


        :return: The error_desc of this RespVoiceprintVerifyMultiResponse.  # noqa: E501
        :rtype: str
        """
        return self._error_desc

    @error_desc.setter
    def error_desc(self, error_desc):
        """Sets the error_desc of this RespVoiceprintVerifyMultiResponse.


        :param error_desc: The error_desc of this RespVoiceprintVerifyMultiResponse.  # noqa: E501
        :type: str
        """

        self._error_desc = error_desc

    @property
    def data(self):
        """Gets the data of this RespVoiceprintVerifyMultiResponse.  # noqa: E501


        :return: The data of this RespVoiceprintVerifyMultiResponse.  # noqa: E501
        :rtype: VoiceprintVerifyMultiResponse
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this RespVoiceprintVerifyMultiResponse.


        :param data: The data of this RespVoiceprintVerifyMultiResponse.  # noqa: E501
        :type: VoiceprintVerifyMultiResponse
        """

        self._data = data

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RespVoiceprintVerifyMultiResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
