#!/usr/bin/env python3

ID_TYPE_APP_ID = "APP_ID"
ID_TYPE_SESSION_ID = "SESSION_ID"

USER_TYPE_DEV = "DEV"
USER_TYPE_PEOPLE = "PEOPLE"
USER_TYPE_VIRTUAL = "VIRTUAL"

TARGET_ACTION_REGISTER = "REGISTER"
TARGET_ACTION_VERIFY = "VERIFY"
TARGET_ACTION_IDENTITY = "IDENTITY"


DATA_FORMAT_WAV = "WAV"
DATA_FORMAT_PCM = "PCM"
